dependencies:
  - dart:
      package: js_interop
      library: js_interop
sanitizer:
  phases:
    - mergeModules
    - mergeInterfaces
    - mergeInterfacesIntoClasses
    - missingTypeArgsAndParams
    - constructorInterfaces
    - invalidIdentifiers
